[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 博客系统

## 管理平台

### 主页

#### 数量总览

#### 访问量趋势折线图

#### 文章趋势折线图图

#### 访问省份饼图

#### 文章分类饼图

#### 文章标签饼图

### 博客管理

#### 分类管理

##### 同步

##### 删除

#### 标签管理

##### 同步

##### 删除

#### 文章管理

##### 同步

##### 上架

##### 下架

##### 预览

##### 删除

### 系统管理

#### 任务管理

#### 博客设置

##### 个人信息

##### Git仓库

##### OSS

## 门户站点
> leftSide=`true`

