[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 博客系统

## 管理平台

### 主页

### 博客管理

#### 分类管理

#### 标签管理

#### 文章管理

### 系统管理

#### 任务管理

#### 博客仓库

#### OSS

#### 个人信息

## 门户站点
> leftSide=`true`

